#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

require 'rubygems'
require 'rails/commands/server'
require 'rack'
require 'webrick'
require 'webrick/https'

#override server defaults options to use ssl
CA_CERT_PATH = "cert/ca/LeadLab_root_cert_TEST.pem"
#SERVER_CERT_PATH = "cert/endpoint.crt"
#SERVER_KEY_PATH = "cert/endpoint.key"
SERVER_CERT_PATH = "cert/ca/LeadLab_root_cert_TEST.pem"
SERVER_KEY_PATH = "cert/ca/LeadLab_root_cert_TEST.pem"

module Rails
  class Server < ::Rack::Server
    def default_options
      super.merge({
                      :environment => (ENV['RAILS_ENV'] || "development").dup,
                      :daemonize => false,
                      :debugger => false,
                      :pid => File.expand_path("tmp/pids/secure_server.pid"),
                      :config => File.expand_path("config.ru"),
                      :SSLEnable => true,
                      :SSLVerifyClient => OpenSSL::SSL::VERIFY_PEER|OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT,
                      :SSLPrivateKey => OpenSSL::PKey::RSA.new(File.open(SERVER_KEY_PATH).read),
                      :SSLCertificate => OpenSSL::X509::Certificate.new(File.open(SERVER_CERT_PATH).read),
                      :SSLCACertificateFile => CA_CERT_PATH,
                      :SSLCertName => [["CN", WEBrick::Utils::getservername]],
                  })
    end
  end
end

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
